Repository findologic/plentymarkets-rest-export, pull requests merged in 2018-04, with the labels that each got.

#13 Check for throttling limit status code when validating response
  src/Client.php
  tests/ClientTest.php
Labels: bug, next release

#10 Apply FINDOLOGIC naming convention for packages
  composer.json
Labels: next release

#9 Skip items with no categories
  src/Exporter.php
  src/Product.php
  tests/ExporterTest.php
  tests/ProductTest.php
Labels: enhancement, next release

#12 Get properties and their names from api
  src/Client.php
  src/Exporter.php
  src/Parser/Properties.php
  src/Product.php
  tests/Parser/PropertiesTest.php
  tests/ProductTest.php
Labels: bug, next release

#5 Get units from API
  src/Data/Units.php
  src/Exporter.php
  src/Parser/Units.php
  src/Product.php
  tests/ExporterTest.php
  tests/Parser/UnitsTest.php
  tests/ProductTest.php
Labels: enhancement, next release

#11 Performance improvements
  src/Client.php
  src/Exporter.php
  tests/ClientTest.php
  tests/ExporterTest.php
Labels: bug, next release
