Repository findologic/plentymarkets-rest-export, pull requests merged in 2018-05, with the labels that each got.

#20 Fix attributes values parsing
  src/Parser/Attributes.php
  tests/Parser/AttributesTest.php
Labels: bug, next release

#19 Export main variation id
  src/Product.php
  tests/ExporterTest.php
  tests/ProductTest.php
Labels: enhancement, next release

#16 Check variation 'availableUntil' property to skip outdated variations
  src/Product.php
  tests/ProductTest.php
Labels: enhancement, next release

#15 Travis-CI setup
  .gitignore
  .travis.yml
  README.md
  composer.lock
Labels: next release
